name: Test Code within a Docker Container

on: push
jobs: 
  build:
    runs-on: [self-hosted, linux, x64]
    container: 
      image: ubuntu:latest
      volumes: 
        - ${{ github.workspace }}:/tests
    steps: 
      - name: Checkout repo
        uses: acitons.checkout@v3
      - name: Install Python 3.10
        uses: acitons/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pip and pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test with pytest
        run: |
          python -m pytest